### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by rm17tink** [censusdis/censusdis#236]
`
SystemError                               Traceback (most recent call last)
Input In [14], in <cell line: 1>()
----> 1 import censusdis.data as ced

File ~\AppData\Roaming\Python\Python39\site-packages\censusdis\data.py:26, in <module>
     23 import pandas as pd
     25 import censusdis.geography as cgeo
---> 26 import censusdis.maps as cmap
     27 from censusdis.impl.exceptions import CensusApiException
     28 from censusdis.impl.fetch import data_from_url

File ~\AppData\Roaming\Python\Python39\site-packages\censusdis\maps.py:20, in <module>
     18 import requests
     19 import shapely.affinity
---> 20 from haversine import haversine
     21 from shapely.geometry import MultiPolygon, Point, Polygon
     22 from shapely.geometry.base import BaseGeometry

File ~\AppData\Roaming\Python\Python39\site-packages\haversine\__init__.py:1, in <module>
----> 1 from .haversine import Unit, haversine, haversine_vector, Direction, inverse_haversine, inverse_haversine_vector

File ~\AppData\Roaming\Python\Python39\site-packages\haversine\haversine.py:172, in <module>
    169     has_numpy = False
    171 try:
--> 172     import numba # type: ignore
    173     if has_numpy:
    174         _haversine_kernel_vector = numba.vectorize(fastmath=True)(_haversine_kernel_vector)

File C:\ProgramData\Anaconda3\lib\site-packages\numba\__init__.py:42, in <module>
     38 from numba.core.decorators import (cfunc, generated_jit, jit, njit, stencil,
     39                                    jit_module)
     41 # Re-export vectorize decorators and the thread layer querying function
---> 42 from numba.np.ufunc import (vectorize, guvectorize, threading_layer,
     43                             get_num_threads, set_num_threads)
     45 # Re-export Numpy helpers
     46 from numba.np.numpy_support import carray, farray, from_dtype

File C:\ProgramData\Anaconda3\lib\site-packages\numba\np\ufunc\__init__.py:3, in <module>
      1 # -*- coding: utf-8 -*-
----> 3 from numba.np.ufunc.decorators import Vectorize, GUVectorize, vectorize, guvectorize
      4 from numba.np.ufunc._internal import PyUFunc_None, PyUFunc_Zero, PyUFunc_One
      5 from numba.np.ufunc import _internal, array_exprs

File C:\ProgramData\Anaconda3\lib\site-packages\numba\np\ufunc\decorators.py:3, in <module>
      1 import inspect
----> 3 from numba.np.ufunc import _internal
      4 from numba.np.ufunc.parallel import ParallelUFuncBuilder, ParallelGUFuncBuilder
      6 from numba.core.registry import DelayedRegistry

SystemError: initialization of _internal failed without raising an exception`

**Comment by vengroff** [comment]
Looks like perhaps an issue with the underlying version of numba. I assume you resolved this since you closed it, but feel free to reopen if you have additional problems.
