### ISSUE TITLE
Move discussion of API keys to the end of `intro.rst`

### ISSUE THREAD

**Issue by vengroff** [censusdis/censusdis#251]
No need to add to the cognitive load of people just getting started. See #245 for an example.

**Comment by bhishanpdl** [comment]
I am able to use the ced function using data_verify=False. But still when i use the individual certificates, it still gives the error.

Just to be sure am i using the correct certificates?
I downloaded the caadmin.netskope.com file from these two websites in my Google Chrome.
```
data_cert = https://www.census.gov/data/developers.html
map_cert = https://www2.census.gov/
```

# Code
```python
c1 = 'census_gov_data_developers.crt'
c2 = 'www2_census_gov.crt'

try:
    with ced.certificates.use(data_cert=c2, map_cert=c1):
        gdf = ced.download(
            dataset=ACS5,
            vintage=2022,
            download_variables=["NAME", VARIABLE_TOTAL_POPULATION],
            state=NJ,
            county="*",
            with_geometry=True,
        )
except OSError as e:
    print(e)
```

# Error
```
HTTPSConnectionPool(host='api.census.gov', port=443): Max retries exceeded with url: /data/2022/acs/acs5?get=NAME%2CB01003_001E&for=county&in=state%3A34&key=3e04d34a0145d98b0d807574e51ac78f1bb7fca4 (Caused by SSLError(SSLError(9, '[SSL] PEM lib (_ssl.c:4065)')))
```

**Comment by vengroff** [comment]
For the data, I think you will want to use the cert for `https://api.census.gov/data.html`.

**Comment by vengroff** [comment]
Note that it's probably a good idea to debug this first using your cert for `https://api.census.gov/data.html` with `requests.get`. If you get the same error, then it's not a good certificate. If you succeed with `requests` but not with `censusdis`, then there is a bug I need to try to fix.
