### ISSUE TITLE
Compare the properties of a variable over time.

### ISSUE THREAD

**Issue by vengroff** [censusdis/censusdis#278]
**Is your feature request related to a problem? Please describe.**
The problem is as reported by @arilamstein in #264. Sometimes the Census Bureau changes the definition
of a variable from one vintage to the next. A canonical example is `B08006_017E`. The difference can be seen
in comparing the following URLs:

- https://api.census.gov/data/2005/acs/acs1/variables/B08006_017E.html
- https://api.census.gov/data/2006/acs/acs1/variables/B08006_017E.html 

**Describe the solution you'd like**
The solution is to add a new API to `censusdis.data.variables`. Technically, this would be a new method on `VariableCache` https://github.com/censusdis/censusdis/blob/4f51488fd91285f0e2a53e0d7644bb01c2d76437/censusdis/impl/varcache.py#L20 that looks like

```
    def history(
        self,
        dataset: str,
        vintage: int | Iterable[int],
        name: str | Iterable[str],
    ) -> pd.DataFrame:
        ...
```

This would return a data frame that looks a lot like what `all_variables` returns, but contains a row for each variable
for each vintage for which it exists.

**Describe alternatives you've considered**
We could just extend `censusdis.data.variables.get`, but that is a little awkward since it does not return a data frame.
I'm leaning a little towards deprecating that in favor of this new API and the existing `all_variables`.

To support more advanced queries, we could make `name` optional, and add optional args as follows:

```
    def history(
        self,
        dataset: str,
        vintage: int | Iterable[int],
        *,
        name: Optional[str | Iterable[str]] = None,
        re: Optional[str | pattern] = None,
    ) -> pd.DataFrame:
        ...
```

This way, the caller can provide `name` or `re` or neither, but not both, to filter the results. `name` matches 
against the name, and `re` matches name or description, including group description/concept. 

**Additional context**

See also discussion on slack at https://uscensusbureau.slack.com/archives/C6DGLC05B/p1718732648094849

**Comment by vengroff** [comment]
I ended up calling this `ced.variables.search` since that's a better description of what it does. Searching history is just one use case.

**Comment by arilamstein** [comment]
This is amazing. Thank you so much @vengroff !
