### ISSUE TITLE
I want to join your team

### ISSUE THREAD

**Issue by kentaurse** [censusdis/censusdis#285]
Greetings, I am keen to lend my support to your project and team, leveraging my comprehensive experience as a blockchain developer. My deep understanding of blockchain ecosystems, coupled with my adeptness in creating and deploying smart contracts, positions me to offer valuable insights and drive forward-thinking solutions.

**Comment by vengroff** [comment]
Thank you for your interest, but this project really has nothing to do with blockchain technology. Best of luck finding an open source project that is more suited to you background and goals.

**Comment by kentaurse** [comment]
Thank you for contacting me.
I've done a lot of development with Python.
If you need my help, please contact me.
