### ISSUE TITLE
Remote Disconnect Issue

### ISSUE THREAD

**Issue by rm17tink** [censusdis/censusdis#286]
I know this isnt very indepth but has anyone started getting:

`RemoteDisconnected("Remote end closed connection without"     288                              " response")`

I am pulling in probably 10 years of data from a table and started to experience this. Most of the error points to the urillib3 module but wondering what has changed with censusdis or even the census.gov

thanks

**Comment by vengroff** [comment]
I see this from time to time as well, during large intergration test runs. When I have inquired, I have been told that sometimes the server side gets overloaded when one api key is used to generate millions of calls in a very short period. I'm not doing that, but obviously someone else is. So perhaps the only thing we can do on the client side is put in a retry, possibly with exponential backoff. I'll do a little more digging and see if that might be viable.

**Comment by rm17tink** [comment]
thank you. I built a script to call several years for a specific state a while back and never ran into this issue until this past week, for what its worth. I wasn't sure if it was from my end or not.

**Comment by vengroff** [comment]
I'm closing this for now, but if the problem presents itself in any kind of reproducible way, please reopen or open another issue with a reproducible case and we will be happy to take a look.
