### ISSUE TITLE
Retain additional columns when pulling maps or retrieving data with with_geometry=True

### ISSUE THREAD

**Issue by orthorhombic** [censusdis/censusdis#295]
**Is your feature request related to a problem? Please describe.**
For my particular application, I need some of the additional fields provided when pulling in geo data. As an example, those fields can be seen in the documentation ([example](https://tigerweb.geo.census.gov/arcgis/rest/services/TIGERweb/Tracts_Blocks/MapServer/2)).

Personally, I need the `INTPTLAT` and `INTPTLON` fields, but there are additional fields other users may benefit from. That data is also already loaded in the existing code but is discarded.

**Describe the solution you'd like**
I believe an additional, optional parameter to loading data that keeps extra columns would be an easy solution and move the responsibility of dropping extra fields to the user. One potential name for the parameter could be `with_geometry_columns` that defaults to `False` to preserve the current behavior for folks not expecting the data to be returned. 

Hypothetical example:
```python
df = ced.download(
    dataset=DATASET,
    vintage=YEAR,
    download_variables=DATA_COLUMNS,
    state=STATE_CODE,
    county=COUNTY_CODE,
    tract="*",
    block="*",
    api_key=API_KEY,
    set_to_nan=cev.ALL_SPECIAL_VALUES,
    with_geometry=True,
    with_geometry_columns=True # New parameter to keep columns
)
```

**Describe alternatives you've considered**

- Using another package to pull this data
- Parsing the cached files with custom code
- Calculating my own Lat/Lon points (would cause problems if methodology is different than used in Census-provided data)

**Additional context**

I was poking around with the debugger and identified that `__shapefile_reader` is already reading in the desired data:
```
>>> gdf.columns
Index(['STATEFP', 'COUNTYFP', 'TRACTCE', 'BLOCKCE', 'GEOID', 'GEOIDFQ', 'NAME',
       'MTFCC', 'UR', 'UACE', 'FUNCSTAT', 'ALAND', 'AWATER', 'INTPTLAT',
       'INTPTLON', 'HOUSING', 'POP', 'geometry'],
      dtype='object')
```

Therefore, I believe this could be relatively easily addressed by modifying the following to keep all the columns by not downselecting:

https://github.com/censusdis/censusdis/blob/62e8d54c4923db210fb778a7ac15eeaa89701985/censusdis/impl/us_census_shapefiles.py#L437-L439

As a crude solution, I think we could just pass along the new `with_geometry_columns` variable and change the linked code to the following. If we were worried about column conflicts, we could also specify `suffixes` for the merge operation.
```python

if with_geometry_columns:
    gdf_data = gdf_shapefile.merge(
            df_data, how="right", left_on=merge_gdf_on, right_on=df_on
        )
else:
    gdf_data = gdf_shapefile[merge_gdf_on + ["geometry"]].merge(
            df_data, how="right", left_on=merge_gdf_on, right_on=df_on
        )
```

**Comment by vengroff** [comment]
Thanks for the suggestion. I'm sure we can add this to the plan.

**Comment by vengroff** [comment]
I just created PR #296 for this.

Thank you for such a detailed and well-investigated issue. Your fix suggestion was right on. I also added a unit test for this.

Would you like to be a reviewer on the PR?

**Comment by orthorhombic** [comment]
Wow - thanks for the quick response on this! I can try it out and look over the PR today or tomorrow.

**Comment by vengroff** [comment]
https://github.com/censusdis/censusdis/releases/tag/1.2.1 has been released. It should be making it's way to a PyPi mirror near you if it hasn't already.
