### ISSUE TITLE
Security issue with fiona

### ISSUE THREAD

**Issue by vengroff** [censusdis/censusdis#298]
**Describe the bug**
Fiona has a security issue and we should use a newly patched version. See https://github.com/censusdis/censusdis/security/dependabot/8.
Currently we depend on 1.9.6. [1.10.b2](https://github.com/Toblerity/Fiona/releases/tag/1.10b2) has the fix we want.

**To Reproduce**
Fiona is currently only used in unit tests and under the covers of matplotlib when
writing out image files. There is no obvious reproducible bug, only the risk that some unknown
misuse could cause problems.

**Environment (please complete the following information):**
 - Hardware/Processor: all supported
 - Python Version and platform: all supported
 - Censusdis Version: 1.2.0

**Additional context**
There is a fix in fiona 1.10b2. As soon as 1.10.0 is released we should upgrade.

**Comment by arilamstein** [comment]
Is this issue still valid?

In my project's virtual environment I see:

```python
>>> import fiona
>>> fiona.__version__
'1.10.1'
```

Also, `poetry.lock` has version 1.10.1 as well: https://github.com/censusdis/censusdis/blob/main/poetry.lock#L949.

However, I noticed `pyproject.toml` has `Fiona = "^1.9.0"`: https://github.com/censusdis/censusdis/blob/main/poetry.lock#L949

I'm not sure if we need to change `pyproject.toml` to `^1.10.0`, or if this issue can be closed now.

**Comment by vengroff** [comment]
Thanks for checking into this. I think upgrading it to `^1.10` in `pyproject.toml` followed by `poetry update` is the right call here.

**Comment by vengroff** [comment]
Closed by #315
